[2025-10-15T02:59:18.853+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-15T02:59:18.963+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: openbrewery_medallion.fetch_bronze scheduled__2025-10-14T00:00:00+00:00 [queued]>
[2025-10-15T02:59:18.978+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: openbrewery_medallion.fetch_bronze scheduled__2025-10-14T00:00:00+00:00 [queued]>
[2025-10-15T02:59:18.979+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-10-15T02:59:19.007+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_bronze> on 2025-10-14 00:00:00+00:00
[2025-10-15T02:59:19.024+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'openbrewery_medallion', 'fetch_bronze', 'scheduled__2025-10-14T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/openbrewery_dag.py', '--cfg-path', '/tmp/tmpuu26rdcu']
[2025-10-15T02:59:19.028+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=184) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-15T02:59:19.029+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask fetch_bronze
[2025-10-15T02:59:19.031+0000] {standard_task_runner.py:64} INFO - Started process 186 to run task
[2025-10-15T02:59:19.191+0000] {task_command.py:426} INFO - Running <TaskInstance: openbrewery_medallion.fetch_bronze scheduled__2025-10-14T00:00:00+00:00 [running]> on host 57afdac7c6b7
[2025-10-15T02:59:21.111+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='marinalvinhaes@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='openbrewery_medallion' AIRFLOW_CTX_TASK_ID='fetch_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-10-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-14T00:00:00+00:00'
[2025-10-15T02:59:21.120+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-15T02:59:22.044+0000] {fetcher.py:37} INFO - Fetched page 1, items=50
[2025-10-15T02:59:40.486+0000] {fetcher.py:37} INFO - Fetched page 2, items=50
[2025-10-15T03:00:36.713+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-15T03:00:36.731+0000] {taskinstance.py:2905} ERROR - Task failed with exception
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:2406)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openbrewerydb.org', port=443): Max retries exceeded with url: /v1/breweries?page=3&per_page=50 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2406)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/openbrewery_dag.py", line 46, in task_fetch
    return run_fetch_and_persist(bronze_dir=BRONZE_DIR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fetcher.py", line 60, in run_fetch_and_persist
    data = fetch_all_breweries()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fetcher.py", line 23, in fetch_all_breweries
    resp = requests.get(API_BASE, params=params, timeout=30)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openbrewerydb.org', port=443): Max retries exceeded with url: /v1/breweries?page=3&per_page=50 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2406)')))
[2025-10-15T03:00:37.258+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=openbrewery_medallion, task_id=fetch_bronze, run_id=scheduled__2025-10-14T00:00:00+00:00, execution_date=20251014T000000, start_date=20251015T025918, end_date=20251015T030037
[2025-10-15T03:00:37.338+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task fetch_bronze (HTTPSConnectionPool(host='api.openbrewerydb.org', port=443): Max retries exceeded with url: /v1/breweries?page=3&per_page=50 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2406)'))); 186)
[2025-10-15T03:00:37.403+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-15T03:00:37.499+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-15T03:00:37.503+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
